openapi: 3.0.0 
info: 
  version: 1.0.0 
  title: node home Work 
  description: node home work api 설계 
servers: 
  # Added by API Auto Mocking Plugin 
  # Added by API Auto Mocking Plugin 
  - description: mini2
    url: http://localhost:3000
paths:
  /user/register:
    post:
      summary: user 회원가입 기능
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userNickname:
                  type: string
                userEmail:
                  type: string
                userPassword:
                  type: string
              example: #sample object
                userNickname: test1
                userEmail: admin@test1.com
                userPassword: test1
      responses:
        '201':
          description: 성공
        '500':
          description: 실패
  /user/auth:
    post:
      summary: 로그인 기능
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userEmail:
                  type: string
                userPassword:
                  type: string
              example: #sample object
                userEmail: admin@test1.com
                userPassword: test1
      responses:
        '201':
          description: 성공
        '500':
          description: 실패
  /user/chkLogin:
    get:
      #로그인할때 헤더로 보내게 해 줌(아래 설명) - 자물쇠 생기게 함
      security: 
        - bearerAuth: []
      summary: 로그인 유저 정보 확인
      responses:
        '201':
          description: 성공
        '500':
          description: 실패
#로그인 인증해주는 component
components: 
  securitySchemes: 
    bearerAuth: 
      type: http 
      scheme: bearer 
      bearerFormat: JWT
#replyRouter
  /user/replyList:
    post:
      summary: 댓글 조회
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userNickname:
                  type: string
                userEmail:
                  type: string
                userPassword:
                  type: string
              example: #sample object
                userNickname: test1
                userEmail: admin@test1.com
                userPassword: test1
      responses:
        '201':
          description: 성공
        '500':
          description: 실패
